name: Bug Report
description: File a bug report.
title: "[Bug 🐛]: "
labels: ["bug", "triage"]
projects: ["ndrewwm/5"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: checkboxes
    id: environment
    attributes:
      label: Environment
      description: What environment are you seeing this issue?
      options:
        - label: Production (Prod)
        - label: Test
    validations:
      required: true
  - type: textarea
    id: errorlog
    attributes:
      label: Relevant log output and/or error messages
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
