name: ✨ New Feature
description: Request a new feature.
title: "[Feature Request]: "
labels: ["enhancement"]
projects: ["ndrewwm/5"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new feature! Filling out the following sections will help us
        prioritize and plan to complete your request.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Who should be the primary person to get in touch with if we need more details?
      placeholder: ex. hello@world.com
    validations:
      required: true
  - type: checkboxes
    id: request-type
    attributes:
      label: Request Type
      description: What kind of request is this?
      options:
        - label: New data source
        - label: New mart
        - label: Updates to an existing mart
  - type: textarea
    id: request-description
    attributes:
      label: What is the nature of this request?
      description: Tell us a bit more about what you need done.
      value: Enter your details here (this form supports Markdown syntax).
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How urgent is this request?
      options:
        - Critical (needed within 1 month)
        - High (needed within 1-3 months)
        - Medium (needed within 3-6 months)
        - Low (flexible timeline)
